version: "3.9"

services:
  currency-exchange-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - currency-network

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: dummypassword
        MYSQL_DATABASE: exchange_db
        MYSQL_USER: exchange_db_user
        MYSQL_PASSWORD: dummyexchange
    networks:
      - currency-network

networks:
  currency-network:
    name: currency-network
    driver: bridge
